services:
  api:
    image: nestjs-api:latest
    container_name: nestjs-api
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - .env
    networks:
      - nestjs_network

networks:
  nestjs_network:
    driver: bridge
